// AUTO-GENERATED by AID/classification_v2/build_treemap_data.py — do not edit.
window.TM_REGION = {"Kenya": "Africa", "Uganda": "Africa", "Mozambique": "Africa", "Nigeria": "Africa", "Côte d'Ivoire": "Africa", "Eswatini": "Africa", "Viet Nam": "Asia", "Indonesia": "Asia", "Philippines": "Asia", "Thailand": "Asia", "Timor-Leste": "Asia", "Fiji": "Pacific", "Palau": "Pacific"};
window.TM_YEARS = [2019, 2020, 2021, 2022, 2023, 2024];
