"""Build the "cross-cutting projects" dataset for crosstech_projects.html.

A cross-cutting project is one whose ENSEMBLE allocation puts at least 15% on
each of at least TWO of the three digital tech types (governance, inclusion,
hard infrastructure). These are the projects that genuinely span multiple
digital domains rather than sitting squarely in one.

Project grain matches the treemap pages: (donor_name, recipient_name,
project_title). For each project we compute the disbursement-weighted, 4-way
normalised ensemble mix [Wg, Wi, Wf, Wnd] (summing to 1 over gov/inc/inf/
non-digital), then keep the project iff >=2 of {Wg, Wi, Wf} are >= THRESH.

Output (one JS file):

  window.TM_CROSSTECH = [
    {t, d, r, fg, disb, commit, W:[Wg,Wi,Wf,Wnd], yrs:[[year,disb,commit],...]},
    ...                      # every qualifying project, sorted by total disbursed
  ]
  window.TM_CROSSTECH_YEARS = [2019, ..., 2024];

fg = funder group: "inst" (EU Institutions) | "mem" (EU member state) | "oth".
All US$ millions.
"""
import json
from pathlib import Path
import pandas as pd

REPO = Path("/Users/robertpraas/Documents/GitHub/cepsai.github.io")
CSV = Path("/Users/robertpraas/CEPS-DST Dropbox/Robert Praas/5-taiwan/experiments_v2/results_v3_1/priority_target_v3_1_classified_ensemble_full.csv")
OUT = REPO / "tm_crosstech.js"

ENS = {"g": "ens_digital_governance_and_rights",
       "i": "ens_digital_human_development",
       "f": "ens_hard_infrastructure",
       "n": "ens_non_digital"}
YEARS = list(range(2019, 2025))
THRESH = 0.15          # >=15% on a tech type to "count"
MIN_TYPES = 2          # need this many digital types over THRESH

EU27 = {"Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia",
        "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
        "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg",
        "Malta", "Netherlands", "Poland", "Portugal", "Romania",
        "Slovak Republic", "Slovenia", "Spain", "Sweden"}
EU_INST = "EU Institutions"


def funder_group(donor):
    if donor == EU_INST:
        return "inst"
    if donor in EU27:
        return "mem"
    return "oth"


def main():
    print("Loading classified CSV …")
    df = pd.read_csv(CSV, low_memory=False)
    df = df[df["year"].isin(YEARS)]
    # EU funders only (Team Europe + member states), matching the donor page scope
    df = df[df["donor_name"].isin(EU27) | (df["donor_name"] == EU_INST)]
    df = df[df["project_title"].fillna("").astype(str).str.strip() != ""].copy()
    print(f"  {len(df):,} EU-funded rows with a project title, {YEARS[0]}-{YEARS[-1]}")

    df["_disb"] = df["usd_disbursement"].fillna(0).astype(float)
    df["_commit"] = df["usd_commitment"].fillna(0).astype(float)
    # per-row 4-way normalised ensemble shares (scale-robust: rows sum to 1 or ~100)
    s4 = sum(df[ENS[c]].fillna(0).astype(float) for c in ("g", "i", "f", "n"))
    for c in ("g", "i", "f", "n"):
        df["_r" + c] = (df[ENS[c]].fillna(0).astype(float) / s4).where(s4 > 0, 0.0)
    df["_s4"] = s4

    rows = []
    keys = ["donor_name", "recipient_name", "project_title"]
    n_groups = df.groupby(keys, sort=False).ngroups
    done = 0
    for (donor, recip, title), g in df.groupby(keys, sort=False):
        done += 1
        if done % 40000 == 0:
            print(f"    {done:,}/{n_groups:,} groups")
        m = g["_s4"] > 0
        if not m.any():
            continue
        w = g.loc[m, "_disb"].clip(lower=0)
        if w.sum() <= 0:                       # no disbursement → weight rows equally
            w = pd.Series(1.0, index=g.index[m])
        W = [float((w * g.loc[m, "_r" + c]).sum() / w.sum()) for c in ("g", "i", "f", "n")]
        tot = sum(W)
        if tot <= 0:
            continue
        W = [x / tot for x in W]
        # cross-cutting test: >=2 of the 3 DIGITAL types over the threshold
        if sum(1 for x in W[:3] if x >= THRESH) < MIN_TYPES:
            continue
        yr = g.groupby("year")[["_disb", "_commit"]].sum()
        yrs = [[int(y), round(float(r["_disb"]), 1), round(float(r["_commit"]), 1)]
               for y, r in yr.iterrows()]
        disb = round(sum(y[1] for y in yrs), 1)
        commit = round(sum(y[2] for y in yrs), 1)
        rows.append({"t": str(title), "d": str(donor), "r": str(recip),
                     "fg": funder_group(donor), "disb": disb, "commit": commit,
                     "W": [round(x, 3) for x in W], "yrs": yrs})

    rows.sort(key=lambda r: -r["disb"])
    OUT.write_text(
        "// AUTO-GENERATED by AID/classification_v2/build_crosstech.py — do not edit.\n"
        "window.TM_CROSSTECH = " + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n"
        "window.TM_CROSSTECH_YEARS = " + json.dumps(YEARS) + ";\n"
    )
    print(f"\nWrote {OUT.name} ({OUT.stat().st_size/1e3:.0f} KB), "
          f"{len(rows):,} cross-cutting projects (>={MIN_TYPES} types over {THRESH:.0%})")

    # ---- headline numbers for the narrative ----
    tot_disb = sum(r["disb"] for r in rows)
    print(f"Total disbursed across them: ${tot_disb/1000:.2f}B")
    print("\nTop 12 by disbursement:")
    for r in rows[:12]:
        wg, wi, wf, wn = r["W"]
        print(f"  ${r['disb']/1000:5.2f}B  g{wg:.2f}/i{wi:.2f}/f{wf:.2f}/nd{wn:.2f}  "
              f"{r['d'][:18]:18s} → {r['r'][:14]:14s}  {r['t'][:42]}")
    # how many hit all THREE digital types
    all3 = sum(1 for r in rows if all(x >= THRESH for x in r["W"][:3]))
    print(f"\n{all3:,} projects clear {THRESH:.0%} on ALL THREE digital types.")


if __name__ == "__main__":
    main()
